# Generated by Django 3.2.3 on 2021-07-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.IntegerField(primary_key=True, serialize=False, verbose_name='identificador de obra')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Obra')),
                ('autor', models.CharField(max_length=30, verbose_name='Autor')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion de obra')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
