# Generated by Django 3.2.3 on 2021-07-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Obra',
            new_name='Arte',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categoriaa',
        ),
        migrations.RenameField(
            model_name='arte',
            old_name='categoria',
            new_name='categoriaa',
        ),
        migrations.RenameField(
            model_name='arte',
            old_name='id_obra',
            new_name='id_arte',
        ),
        migrations.RenameField(
            model_name='categoriaa',
            old_name='nombreCategoria',
            new_name='nombreCategoriaa',
        ),
    ]
